### PR TITLE
Feature/welcome email

### PR DESCRIPTION
**Pull request by snehabanda30**
Just updated with the email template

### CODE REVIEW

**Review by ezrizhu — CHANGES_REQUESTED** [review]
If we're sending html emails, we should also attach a plain text copy for users without a html email reader.

**Comment by snehabanda30** [comment]
I am just a little bit confused on how to approach the change. Should I create a html file with just the text and no other html or css?

**Comment by ezrizhu** [comment]
keep the html, but also attach a plain text version of the email

**Comment by snehabanda30** [comment]
Sorry, I just want to confirm. Should I have a link that goes to the plain text version?

**Comment by ezrizhu** [comment]
no, please see https://stackoverflow.com/questions/28111945/adding-a-plain-text-fallback-with-html-email

**Comment by miguel-merlin** [comment]
@snehabanda30 Do you need help with addressing the comments to the PR?

**Comment by snehabanda30** [comment]
My apologies! I was caught up with a few assignments. I need to add in the inline css.

**Comment by snehabanda30** [comment]
Just committed the inline css changes. Let me know if there is anything else I should add.

**Pull request closed without merging**
